### ISSUE TITLE
Add Permalink to show notes page in Libsyn

### ISSUE THREAD

**Issue by abhijit86k** [OpelexProject/OpelexProject.github.io#9]
- [x]	Ep.10 - Interview with Girish Kamath
- [x]	Ep.9 - Interview with Kartik Iyer
- [x]	Ep.8 - Interview with Jonathan Maisonneuve
- [x]	Ep.7 - Interview with Manoj R
- [x]	Ep.6 - Interview with Sheldon Williamson
- [x]	Ep.5 - Interview with Dr. Jemimah Akiror
- [x]	Ep.4 - Interview with Ashwin Khambadkone
- [x]	Ep.3 - Interview with Ned Mohan
- [x]	Ep.2 - Interview with L. Umanand
- [x]	Ep.1 - The Pilot
- [x]	Ep.0 - Introducing the Opelex Podcast

**Comment by fthndr** [comment]
``

**Comment by abhijit86k** [comment]
Updated Libsyn. I think users who have already downloaded the feed may have to clear the cache and download again, but for new users and new espisodes this should work fine.
